# Generated by Django 4.0.6 on 2022-07-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('iso2', models.TextField(blank=True, null=True)),
                ('numeric_code', models.TextField(blank=True, null=True)),
                ('phone_code', models.TextField(blank=True, null=True)),
                ('capital', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('currency_name', models.TextField(blank=True, null=True)),
                ('currency_symbol', models.TextField(blank=True, null=True)),
                ('tld', models.TextField(blank=True, null=True)),
                ('native', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('subregion', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('emoji', models.TextField(blank=True, null=True)),
                ('emojiU', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('state_code', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('state_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
        ),
    ]
