# Generated by Django 4.0.6 on 2022-07-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_country_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country_id',
            new_name='country',
        ),
    ]
